spring:
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  redis:
    host: ${REDISHOST}
    port: ${REDISPORT}
    password: ${REDIS_PASSWORD}

  cache:
    type: redis